apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bivac.fullname" . }}
  labels:
    app: {{ template "bivac.name" . }}
    chart: {{ template "bivac.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

