apiVersion: v1
kind: Template
metadata:
  name: bivac
  annotations:
    description: "Bivac lets you backup all your containers volumes deployed on Docker Engine or Kubernetes using Restic, Duplicity or RClone."
    tags: "backup,duplicity,restic,rclone,volume"
objects:
- apiVersion: batch/v2alpha1
  kind: CronJob
  metadata:
    name: ${APP_NAME}
  spec:
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
    schedule: "${SCHEDULE}"
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              app: ${APP_NAME}
          spec:
            serviceAccountName: ${APP_NAME}
            containers:
              - name: bivac
                image: "${BIVAC_IMAGE}"
                imagePullPolicy: Always
                env:
                  - name: BIVAC_ORCHESTRATOR
                    value: kubernetes
                  - name: BIVAC_TARGET_URL
                    value: ${BIVAC_TARGET_URL}
                  - name: AWS_ACCESS_KEY_ID
                    value: ${AWS_ACCESS_KEY_ID}
                  - name: AWS_SECRET_ACCESS_KEY
                    value: ${AWS_SECRET_ACCESS_KEY}
                  - name: SWIFT_USERNAME
                    value: ${SWIFT_USERNAME}
                  - name: SWIFT_PASSWORD
                    value: ${SWIFT_PASSWORD}
                  - name: SWIFT_AUTHURL
                    value: ${SWIFT_AUTHURL}
                  - name: SWIFT_TENANTNAME
                    value: ${SWIFT_TENANTNAME}
                  - name: SWIFT_REGIONNAME
                    value: ${SWIFT_REGIONNAME}
                  - name: RESTIC_PASSWORD
                    value: ${RESTIC_PASSWORD}
                  - name: K8S_WORKER_SERVICE_ACCOUNT
                    value: ${K8S_WORKER_SERVICE_ACCOUNT}
            restartPolicy: OnFailure
- kind: Role
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - create
    - delete
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - pods/log
    - pods/exec
    verbs:
    - get
    - post
    - create
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${APP_NAME}
- kind: RoleBinding
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
  roleRef:
    name: ${APP_NAME}
    namespace: ${NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: ${APP_NAME}
parameters:
- name: APP_NAME
  description: Name use for all bivac objects. This name should be unique across project.
  value: bivac
- name: BIVAC_IMAGE
  description: Name of bivac docker image to use, including tag.
  value: 'camptocamp/bivac:latest'
- name: SCHEDULE
  description: "Cron format schedule specification. Ex: '0 * * * *' backup every hour."
  value: "0 2 * * *"
- name: BIVAC_TARGET_URL
  description: The target URL to push backup to.
- name: AWS_ACCESS_KEY_ID
  description: The AWS access key ID (optional).
  value: ""
- name: AWS_SECRET_ACCESS_KEY
  description: The AWS secret access key (optional).
  value: ""
- name: SWIFT_USERNAME
  description: The Swift user name (optional).
  value: ""
- name: SWIFT_PASSWORD
  description: The Swift password (optional).
  value: ""
- name: SWIFT_AUTHURL
  description: The Swift auth URL (optional).
  value: ""
- name: SWIFT_TENANTNAME
  description: The Swift tenant name (optional).
  value: ""
- name: SWIFT_REGIONNAME
  description: The Swift region name (optional).
  value: ""
- name: RESTIC_PASSWORD
  description: The restic backup password.
- name: K8S_WORKER_SERVICE_ACCOUNT
  description: Kubernetes service account to use for workers.
  value: useroot
- name: NAMESPACE
  description: Openshift project name (namespace)
labels:
  app: bivac
